"""initial

Revision ID: 1a5a8bb80cda
Revises: 
Create Date: 2026-05-15 20:04:34.740310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5a8bb80cda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('sexe', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('date_inscription', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('administrateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medecins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ordre', sa.String(length=50), nullable=False),
    sa.Column('localisation', sa.String(length=255), nullable=True),
    sa.Column('tarif_consultation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disponibilite', sa.Boolean(), nullable=False),
    sa.Column('note_moyenne', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ordre')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_avis', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carnets_sante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('antecedents', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('groupe_sanguin', sa.String(length=5), nullable=True),
    sa.Column('maladies_chroniques', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_derniere_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('ordonnances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicaments', sa.Text(), nullable=False),
    sa.Column('posologie', sa.Text(), nullable=False),
    sa.Column('date_emission', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orientations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_structure', sa.String(length=100), nullable=False),
    sa.Column('nom_structure', sa.String(length=255), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('localisation', sa.String(length=255), nullable=True),
    sa.Column('date_orientation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medecin_id')
    )
    op.create_table('rendez_vous',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('date_paiement', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rendez_vous_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rendez_vous_id'], ['rendez_vous.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rendez_vous_id')
    )
    op.create_table('teleconsultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=True),
    sa.Column('lien_video', sa.String(length=512), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('compte_rendu', sa.Text(), nullable=True),
    sa.Column('rendez_vous_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rendez_vous_id'], ['rendez_vous.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rendez_vous_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teleconsultations')
    op.drop_table('paiements')
    op.drop_table('rendez_vous')
    op.drop_table('orientations')
    op.drop_table('ordonnances')
    op.drop_table('carnets_sante')
    op.drop_table('avis')
    op.drop_table('patients')
    op.drop_table('medecins')
    op.drop_table('administrateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
